=== YashSampat23154/Distributed-AI-IOT-Based-Application-Deployment-Platform/platform--validator-workflow/contracts/configSchema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "language": {
        "type": "string"
      },
      "workdir": {
        "type": "string"
      },
      "port": {
        "type": "string"
      },
      "command": {
        "type": "string"
      },
      "packages_file_path": {
        "type": "string"
      },
      "package_installation_cmd": {
        "type": "string"
      }
    },
    "required": [
      "language",
      "workdir",
      "port",
      "command",
      "packages_file_path",
      "package_installation_cmd"
    ]
  }

=== YashSampat23154/Distributed-AI-IOT-Based-Application-Deployment-Platform/platform--monitoring-fault-tolerance/config.json
{
	"language": "python:3.10-alpine",
	"workdir": "/Monitoring-Fault-Tolerance",
	"port": "8112",
	"command": "python3 /Monitoring-Fault-Tolerance/monitoring.py",
	"packages_file_path": "/Monitoring-Fault-Tolerance/requirements.txt",
	"package_installation_cmd": "pip install -r /Monitoring-Fault-Tolerance/requirements.txt"
}
